# Docker Compose file for WordPress with File Browser, phpMyAdmin, and Plugin Installer
#
# This stack now builds a custom WordPress image using a Dockerfile.
#
# To run this:
# 1. Save all files: 'docker-compose.yml', 'Dockerfile', 'install-plugins.sh', 'uploads.ini', '.env'.
# 2. Make the script executable: `chmod +x install-plugins.sh`.
# 3. Run 'docker-compose up -d --build' in your terminal.
#
# Access WordPress at: The URL you set in WORDPRESS_SITE_URL (e.g., http://localhost:8080)
# Access File Browser at: http://localhost:8081 (Default user/pass: admin/admin)
# Access phpMyAdmin at: http://localhost:8082

version: '3.8'

services:
  # WordPress Service (built from Dockerfile)
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_app
    restart: always
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL} # Define your site URL
    volumes:
      - ./wordpress:/var/www/html # Mount WordPress files to a local directory
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini # Mount custom PHP config
    depends_on:
      - db

  # MariaDB Database Service
  db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql # Persist database data

  # File Browser Service (Web-based File Manager)
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: wordpress_file_manager
    restart: always
    ports:
      - "8081:80" # Map host port 8081 to container port 80
    volumes:
      - ./wordpress:/srv # Mount the same WordPress directory to be managed
      - ./filebrowser.db:/database.db # Persist File Browser's database
    user: "root" # Run as root to have permission to manage WordPress files

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wordpress_phpmyadmin
    restart: always
    ports:
      - "8082:80" # Map host port 8082 to container port 80
    environment:
      PMA_HOST: db # Connect to the 'db' service
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Provide root password for full access
    depends_on:
      - db

volumes:
  db_data:
  wordpress:

